# Generated by Django 2.2.1 on 2019-05-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=30)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('birthdate_hidden', models.BooleanField(default=False)),
            ],
        ),
    ]
