# Generated by Django 2.2.1 on 2019-05-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1_injection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=70)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('birthdate_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
