# Generated by Django 2.2.1 on 2019-05-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1_injection', '0002_auto_20190524_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
